export const THEME = {
 primary: '#FF9A3D',
  secondary: '#FFF7D0',
  tertiary: '#E8F4FF',
  neutral: '#FFFFFF',
  accent: '#FFD166',
  success: '#4ECDC4',
  header: '#fcf8b1',
  text: {
    primary: '#2D4A63',
    secondary: '#6B7B8C',
    light: '#FFFFFF',
    dark: '#4A5C6B',
    accent: '#E53E3E',
  }
};

export const localImages = {
  kaaba: require('../assets/images/kaaba.png'),
  dua_1: require('../assets/images/kaaba.png'),
  dua_2: require('../assets/images/dua_2.png'),
  dua_3: require('../assets/images/dua_3.png'),
  dua_4: require('../assets/images/dua_4.png'),
  dua_5: require('../assets/images/dua_5.png'),
  dua_6: require('../assets/images/dua_6.png'),
  dua_7: require('../assets/images/dua_7.png'),
  dua_8: require('../assets/images/dua_8.png'),
  dua_9: require('../assets/images/dua_9.png'),
  dua_10: require('../assets/images/dua_10.png'),
  dua_11: require('../assets/images/dua_11.png'),
  dua_12: require('../assets/images/dua_12.png'),
  dua_13: require('../assets/images/dua_13.png'),
  dua_14: require('../assets/images/dua_14.png'),
  dua_15: require('../assets/images/dua_15.png'),
  dua_16: require('../assets/images/dua_16.png'),
  dua_17: require('../assets/images/dua_17.png'),
  dua_18: require('../assets/images/dua_18.png'),
  dua_19: require('../assets/images/dua_19.png'),
  dua_20: require('../assets/images/dua_20.png'),
  dua_21: require('../assets/images/dua_21.png'),
  dua_22: require('../assets/images/dua_22.png'),
  dua_23: require('../assets/images/dua_23.png'),
  dua_24: require('../assets/images/dua_24.png'),
  dua_25: require('../assets/images/dua_25.png'),
  dua_26: require('../assets/images/dua_26.png'),
  dua_27: require('../assets/images/dua_27.png'),
  dua_28: require('../assets/images/dua_28.png'),
  dua_29: require('../assets/images/dua_29.png'),
  dua_30: require('../assets/images/dua_30.png'),
  dua_31: require('../assets/images/dua_31.png'),
  dua_32: require('../assets/images/dua_32.png'),
};

export const BUTTON_IMAGES = {
  previous: require('../assets/btns/btn_back.png'),
  next: require('../assets/btns/btn_next.png'),
  pause: require('../assets/btns/btn_pause.png'),
  play: require('../assets/btns/btn_play.png'),
  repeat: require('../assets/btns/btn_repeat.png'),
  home: require('../assets/btns/btn_setting.png'),
};
